### ISSUE TITLE
Error when using JSON annotation

### ISSUE THREAD

**Issue by dukenguyenxyz** [elbywan/openapi-generator#10]
The documentation implies quite clearly that `OpenAPI::Generator::Serializable` is built to interop with `JSON::Serializable`, including using with `@[JSON::Field]` annotation. However, when the following code is executed (this is taken from [1](https://github.com/elbywan/openapi-generator/blob/16dab524e1b74eeb6a271b7d34c36788ec13f591/spec/spec_helper.cr#L49-L73), [2](https://github.com/elbywan/openapi-generator/blob/16dab524e1b74eeb6a271b7d34c36788ec13f591/spec/core/model_spec.cr#L8-L9), with the sole addition of `@[JSON::Field(key: "array_of_int")]` to `property array_of_int`)

```crystal
  require "spec"
  require "json"
  require "../src/openapi-generator"

  struct InnerModel
    extend OpenAPI::Generator::Serializable
    include JSON::Serializable

    @[JSON::Field(key: "array_of_int")]
    @[OpenAPI::Field(write_only: true)]
    property array_of_int : Array(Int32)

    SCHEMA = <<-JSON
    {
      "required": [
        "array_of_int"
      ],
      "type": "object",
      "properties": {
        "array_of_int": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "writeOnly": true
        }
      }
    }
    JSON
  end

  json_schema = ::Model::ComplexModel.generate_schema.to_pretty_json
  json_schema.should eq ::Model::ComplexModel::SCHEMA

```

the following error is thrown:

```crystal

 8 | inner_schema = ::Model::InnerModel.generate_schema.to_pretty_json
                                        ^--------------
Error: instantiating 'Model::InnerModel.class#generate_schema()'


In spec/spec_helper.cr:53:24

 53 | @[JSON::Field(key: "array_of_int")]
                         ^
Error: expecting token ']', not 'array_of_int'
```

**Comment by elbywan** [comment]
@dukeraphaelng Thanks for the report, there seems to be an issue when using a string argument. (`key: "array_of_int"`/ `key: :array_of_int`)

I've pushed a commit that should fix it.

**Comment by dukenguyenxyz** [comment]
thank you so much!
