### ISSUE TITLE
Bug: compiler does not generate param/ rendering values if macros are called from helper methods

### ISSUE THREAD

**Issue by dukenguyenxyz** [elbywan/openapi-generator#21]
This would not work because `macro param` is not declared directly in the method body of the route, but in a helper method which is then called in the route method body.

```crystal
require "openapi-generator"

class ActionControllerSpec::Payload
  include JSON::Serializable
  extend OpenAPI::Generator::Serializable

  def initialize(@mandatory : String, @optional : Bool?, @with_default : String, @with_default_nillable : String?)
  end
end

class HelperSpecActionController < ActionController::Base
  include ::OpenAPI::Generator::Controller
  include ::OpenAPI::Generator::Helpers::ActionController

  base "/hello"

  @[OpenAPI(
    <<-YAML
      summary: get all payloads
    YAML
  )]
  def index
    render json: [ActionControllerSpec::Payload.new("mandatory", true, "default", "nillable")], description: "all payloads", type: Array(ActionControllerSpec::Payload)
  end

  @[OpenAPI(
    <<-YAML
      summary: Sends a hello payload
      responses:
        200:
          description: Overriden
    YAML
  )]
  def create
    mandatory = param mandatory : String, "A mandatory query parameter"
    optional = param optional : Bool?, "An optional query parameter"
    with_default = param with_default : String = "default_value", "A mandatory query parameter with default"
    with_default_nillable = param with_default_nillable : String? = "default_value_nillable", "An optional query parameter with default"

    body_as ActionControllerSpec::Payload?, description: "A Hello payload."

    payload = ActionControllerSpec::Payload.new(mandatory, optional, with_default, with_default_nillable)

    render json: get_item, description: "all g"
  end

  private def get_item
    instance_id = param instance_id : Int32? = 0, description: "instance's id"
    is_recorded = param is_recorded : Bool? = false, description: "recorded status"

    is_recorded ? instance_id : nil
  end
end

OpenAPI::Generator::Helpers::ActionController.bootstrap

options = {
  output: Path[Dir.current] / "openapi_test.yaml",
}
base_document = {
  info:       {title: "Test", version: "0.0.1"},
  components: NamedTuple.new,
}

OpenAPI::Generator.generate(
  OpenAPI::Generator::RoutesProvider::ActionController.new,
  options: options,
  base_document: base_document
)

openapi_file_contents = File.read "openapi_test.yaml"
```

**Comment by elbywan** [comment]
Hi @dukeraphaelng,

> This would not work because macro param is not declared directly in the method body of the route, but in a helper method which is then called in the route method body.

This is actually not a bug *per se* but a limitation of the generator logic (relying on the method name to bind inference to a specific function). Calling the macros from a nested method won't work without giving some hints to the generator during compilation.

I can understand that this is frustrating, so here are two ways of mitigating the problem:

1) Turn the `def` into a `macro`:

```crystal
private macro get_item
  # ...
end
```

2) I pushed a commit that added an annotation argument that will force-bind the macro called in a method to another method:

```crystal
@[OpenAPI(dependency: create) # "create" beeing the other method name
private def get_item
  # ...
end
```

It might be possible to store the controller methods call stack (and order) during compilation and auto-bind to the first method, but I think this is a bit overkill and time consuming. I think the above solutions should be good enough for now!

**Comment by dukenguyenxyz** [comment]
Thank you @elbywan for the quick response! I need some more time to think about this issue as well as your solution. However, just for now, I do have one comment: the `dependency` annotation named arg should probably be an array since a private method can be used in multiple route method bodies.

**Comment by elbywan** [comment]
@dukeraphaelng Good catch, I added a `dependencies` named argument as well. 👍 

` @[OpenAPI(dependencies: { a, b, c })`

**Comment by dukenguyenxyz** [comment]
There's another bruteforce-lite way we can handle this which might be slightly more elegant.

- Define a macro block that wraps a method call where a helper macro is expected to be used
```crystal
macro expand_methods(&block)
end
```

- Methods called inside the block will be added with the 'dependencies'.

I only have a vague idea of this. If you don't find it possible or effective to implement this I think we can just move on with your current implementation.

**Comment by elbywan** [comment]
> It might be possible to store the controller methods call stack (and order) during compilation and auto-bind to the first method

@dukeraphaelng Actually implementing the above idea was easier than I thought 😄. I pushed https://github.com/elbywan/openapi-generator/commit/9a23f5d891f238842223b424f42909666233752c that should require zero input from the library consumer and work out of the box.
